server:
  port: 8081

logging:
  config: classpath:logback.xml

adms:
  job:
    admin:
      addresses: http://127.0.0.1:8080
    executor:
      appname: datax-executor
      ip:
      port: 9999
    accessToken: